[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CLImod"
authors = [{name = "Ghostling225", email = "wojcikadam742@gmail.com"}]
dynamic = ["version", "description"]
